export const RELIGION = [
  "ISLAM",
  "KRISTEN",
  "KATOLIK",
  "HINDU",
  "BUDDHA",
  "KHONGHUCU",
] as const;

export const MARITAL_STATUS = [
  "BELUM KAWIN",
  "KAWIN",
  "CERAI HIDUP",
  "CERAI MATI",
] as const;

export const JOB = [
  "PEGAWAI NEGERI SIPIL",
  "TNI",
  "POLRI",
  "HAKIM",
  "JAKSA",
  "ADVOKAT",
  "NOTARIS",
  "PEJABAT PEMERINTAHAN",
  "KARYAWAN SWASTA",
  "WIRASWASTA",
  "PEDAGANG",
  "PENGUSAHA",
  "DIREKTUR",
  "MANAGER",
  "SUPERVISOR",
  "MARKETING",
  "SALES",
  "ADMINISTRASI",
  "GURU",
  "DOSEN",
  "KEPALA SEKOLAH",
  "TUTOR",
  "INSTRUKTUR",
  "PENELITI",
  "MAHASISWA",
  "PELAJAR",
  "DOKTER",
  "PERAWAT",
  "BIDAN",
  "APOTEKER",
  "DOKTER GIGI",
  "AHLI GIZI",
  "FISIOTERAPIS",
  "PARAMEDIS",
  "RADIOGRAFER",
  "PETANI",
  "PETERNAK",
  "NELAYAN",
  "PEMBUDIDAYA IKAN",
  "BURUH TANI",
  "TEKNISI",
  "MONTIR",
  "MEKANIK",
  "PROGRAMMER",
  "ANALIS SISTEM",
  "NETWORK ADMINISTRATOR",
  "IT SUPPORT",
  "ENGINEER",
  "ARSITEK",
  "AKUNTAN",
  "TELLER",
  "CUSTOMER SERVICE",
  "ANALIS KREDIT",
  "KONSULTAN KEUANGAN",
  "KASIR",
  "SUPIR",
  "DRIVER",
  "OJEK ONLINE",
  "KURIR",
  "PILOT",
  "MASINIS",
  "KONDEKTUR",
  "EKSPEDISI",
  "PRAMUSAJI",
  "RESEPSIONIS",
  "CHEF",
  "KOKI",
  "BARTENDER",
  "ROOM BOY",
  "HOUSEKEEPING",
  "SECURITY",
  "CLEANING SERVICE",
  "WARTAWAN",
  "EDITOR",
  "FOTOGRAFER",
  "VIDEOGRAPHER",
  "DESAINER GRAFIS",
  "SENIMAN",
  "PENULIS",
  "CONTENT CREATOR",
  "YOUTUBER",
  "BLOGGER",
  "INFLUENCER",
  "USTADZ",
  "PENDETA",
  "PASTOR",
  "IMAM",
  "GURU NGAJI",
  "MUBALIGH",
  "ROHANIWAN",
  "KONSULTAN",
  "PSIKOLOG",
  "KONSELOR",
  "AUDITOR",
  "SURVEYOR",
  "MAKELAR",
  "AGEN ASURANSI",
  "TUKANG",
  "TUKANG BATU",
  "TUKANG KAYU",
  "TUKANG LAS",
  "TUKANG CAT",
  "BURUH BANGUNAN",
  "MANDOR",
  "BURUH",
  "OPERATOR MESIN",
  "QUALITY CONTROL",
  "FOREMAN",
  "WELDER",
  "PENSIUNAN",
  "IBU RUMAH TANGGA",
  "FREELANCER",
  "PEKERJA LEPAS",
  "TIDAK BEKERJA",
  "BELUM BEKERJA",
] as const;

export const BLOOD_TYPE = [
  "A+",
  "A-",
  "B+",
  "B-",
  "AB+",
  "AB-",
  "O+",
  "O-",
] as const;

export const KTP_DEFAULTS = {
  dataCount: 10,
  minAge: 18,
  maxAge: 60,
  gender: "BOTH" as const,
};

export const KTA_DEFAULTS = {
  dataCount: 10,
  minAge: 1,
  maxAge: 16,
  gender: "BOTH" as const,
};

export const STORAGE_KEYS = {
  ktpSettings: "ktp-generator-settings",
  ktaSettings: "kta-generator-settings",
  ktpPosition: "ktp-generator-position-config",
  ktaPosition: "kta-generator-position-config",
} as const;

export const KTP_TEMPLATE_PATH = "/KTP Template.png";
export const KTA_TEMPLATE_PATH = "/KTA Template.png";
