export const provinceData = [
  {
    name: "DKI JAKARTA",
    code: "31",
    city: [
      "JAKARTA PUSAT",
      "JAKARTA UTARA",
      "JAKARTA SELATAN",
      "JAKARTA TIMUR",
      "JAKARTA BARAT",
      "KEPULAUAN SERIBU",
    ],
  },
  {
    name: "JAWA BARAT",
    code: "32",
    city: [
      "BANDUNG",
      "BOGOR",
      "DEPOK",
      "CIMAHI",
      "BEKASI",
      "TASIKMALAYA",
      "BANJAR",
      "SUKABUMI",
      "CIREBON",
    ],
  },
  {
    name: "JAWA TENGAH",
    code: "33",
    city: [
      "SEMARANG",
      "SURAKARTA",
      "MAGELANG",
      "SALATIGA",
      "PEKALONGAN",
      "TEGAL",
    ],
  },
  {
    name: "JAWA TIMUR",
    code: "35",
    city: [
      "SURABAYA",
      "MALANG",
      "MADIUN",
      "KEDIRI",
      "BLITAR",
      "MOJOKERTO",
      "PASURUAN",
      "PROBOLINGGO",
      "BATU",
    ],
  },
  {
    name: "BANTEN",
    code: "36",
    city: ["TANGERANG", "TANGERANG SELATAN", "CILEGON", "SERANG"],
  },
  {
    name: "SUMATERA UTARA",
    code: "12",
    city: [
      "MEDAN",
      "BINJAI",
      "TEBING TINGGI",
      "PEMATANGSIANTAR",
      "TANJUNGBALAI",
      "SIBOLGA",
      "PADANGSIDIMPUAN",
      "GUNUNGSITOLI",
    ],
  },
  {
    name: "SUMATERA BARAT",
    code: "13",
    city: [
      "PADANG",
      "BUKITTINGGI",
      "PADANGPANJANG",
      "PAYAKUMBUH",
      "PARIAMAN",
      "SAWAHLUNTO",
      "SOLOK",
    ],
  },
  {
    name: "SUMATERA SELATAN",
    code: "16",
    city: ["PALEMBANG", "PRABUMULIH", "PAGAR ALAM", "LUBUKLINGGAU"],
  },
  {
    name: "RIAU",
    code: "14",
    city: ["PEKANBARU", "DUMAI"],
  },
  {
    name: "KEPULAUAN RIAU",
    code: "21",
    city: ["BATAM", "TANJUNG PINANG"],
  },
  {
    name: "LAMPUNG",
    code: "18",
    city: ["BANDAR LAMPUNG", "METRO"],
  },
  {
    name: "KALIMANTAN BARAT",
    code: "61",
    city: ["PONTIANAK", "SINGKAWANG"],
  },
  {
    name: "KALIMANTAN TENGAH",
    code: "62",
    city: ["PALANGKA RAYA"],
  },
  {
    name: "KALIMANTAN SELATAN",
    code: "63",
    city: ["BANJARMASIN", "BANJARBARU"],
  },
  {
    name: "KALIMANTAN TIMUR",
    code: "64",
    city: ["SAMARINDA", "BALIKPAPAN", "BONTANG"],
  },
  {
    name: "KALIMANTAN UTARA",
    code: "65",
    city: ["TARAKAN"],
  },
  {
    name: "SULAWESI UTARA",
    code: "71",
    city: ["MANADO", "BITUNG", "TOMOHON", "cityMOBAGU"],
  },
  {
    name: "SULAWESI TENGAH",
    code: "72",
    city: ["PALU"],
  },
  {
    name: "SULAWESI SELATAN",
    code: "73",
    city: ["MAKASSAR", "PALOPO", "PAREPARE"],
  },
  {
    name: "SULAWESI TENGGARA",
    code: "74",
    city: ["KENDARI", "BAU-BAU"],
  },
  {
    name: "GORONTALO",
    code: "75",
    city: ["GORONTALO"],
  },
  {
    name: "SULAWESI BARAT",
    code: "76",
    city: ["MAMUJU"],
  },
  {
    name: "BALI",
    code: "51",
    city: ["DENPASAR"],
  },
  {
    name: "NUSA TENGGARA BARAT",
    code: "52",
    city: ["MATARAM", "BIMA"],
  },
  {
    name: "NUSA TENGGARA TIMUR",
    code: "53",
    city: ["KUPANG"],
  },
  {
    name: "MALUKU",
    code: "81",
    city: ["AMBON", "TUAL"],
  },
  {
    name: "MALUKU UTARA",
    code: "82",
    city: ["TERNATE", "TIDORE KEPULAUAN"],
  },
  {
    name: "PAPUA BARAT",
    code: "91",
    city: ["SORONG"],
  },
  {
    name: "PAPUA",
    code: "94",
    city: ["JAYAPURA"],
  },
  {
    name: "DI YOGYAKARTA",
    code: "34",
    city: ["YOGYAKARTA"],
  },
  {
    name: "ACEH",
    code: "11",
    city: ["BANDA ACEH", "SABANG", "LHOKSEUMAWE", "LANGSA", "SUBULUSSALAM"],
  },
  {
    name: "JAMBI",
    code: "15",
    city: ["JAMBI", "SUNGAI PENUH"],
  },
  {
    name: "BENGKULU",
    code: "17",
    city: ["BENGKULU"],
  },
  {
    name: "BANGKA BELITUNG",
    code: "19",
    city: ["PANGKAL PINANG"],
  },
];

export const maleName = [
  "AHMAD",
  "MUHAMMAD",
  "ABDUL",
  "AGUS",
  "BUDI",
  "BAMBANG",
  "DEDI",
  "EDI",
  "FERRY",
  "GUNAWAN",
  "HADI",
  "INDRA",
  "JOKO",
  "KURNIAWAN",
  "LESTARI",
  "MADE",
  "NUGROHO",
  "OKI",
  "PUTRA",
  "RAHAYU",
  "SARI",
  "TONO",
  "USMAN",
  "VINO",
  "WAHYU",
  "XANDER",
  "YUSUF",
  "ZAKI",
  "ARIEF",
  "BAGUS",
  "CANDRA",
  "DARMAWAN",
  "ERIK",
  "FAJAR",
  "GALIH",
  "HENDRA",
  "IMAM",
  "JAKA",
  "KEVIN",
  "LUTFI",
  "MOCHAMAD",
  "NOVA",
  "OSCAR",
  "PRAYOGA",
  "QOMAR",
  "RUDI",
  "SIGIT",
  "TEGUH",
  "ULIL",
  "VIKI",
  "WAWAN",
  "XALIM",
  "YOGI",
  "ZAINAL",
  "ADHI",
  "BAYU",
  "CHAIRUL",
  "DONI",
  "EFENDI",
  "FIRMANSYAH",
];

export const femaleName = [
  "SITI",
  "NUR",
  "DEWI",
  "RINA",
  "LILIS",
  "MAYA",
  "RATNA",
  "WATI",
  "YUNI",
  "ENDANG",
  "FATIMAH",
  "INDAH",
  "KARTIKA",
  "NURUL",
  "PUTRI",
  "RETNO",
  "SUCI",
  "TUTI",
  "VITA",
  "WIDYA",
  "ANIS",
  "BUDI",
  "CITRA",
  "DIAN",
  "EKA",
  "FITRI",
  "GITA",
  "HESTI",
  "IKA",
  "JULIA",
  "KIRANA",
  "LINDA",
  "MELATI",
  "NOVI",
  "OKY",
  "PUSPITA",
  "QORY",
  "ROSA",
  "SILVI",
  "TINA",
  "UMI",
  "VERA",
  "WULAN",
  "XENIA",
  "YASMIN",
  "ZULFA",
  "APRILIA",
  "BUNGA",
  "CYNTIA",
  "DILA",
  "ERMA",
  "FIRA",
  "GALUH",
  "HANA",
  "INTAN",
  "JIHAN",
  "KIKI",
  "LALA",
  "MIRNA",
  "NITA",
];

export const familyName = [
  "PRATAMA",
  "WIBOWO",
  "KURNIAWAN",
  "SARI",
  "LESTARI",
  "BUDI",
  "RAHAYU",
  "SANTOSO",
  "WIJAYA",
  "SUSANTO",
  "HANDOKO",
  "SAPUTRA",
  "WARDANI",
  "HIDAYAT",
  "RAHMAN",
  "PERMANA",
  "SETIAWAN",
  "MARTONO",
  "SUTRISNO",
  "PURNOMO",
  "SURYANTO",
  "GUNAWAN",
  "PRASETYO",
  "HARTONO",
  "NUGROHO",
  "UTOMO",
  "SUPARDI",
  "DARMAWAN",
  "ISMANTO",
  "PRIYADI",
];

export const birthPlace = [
  "JAKARTA",
  "SURABAYA",
  "BANDUNG",
  "MEDAN",
  "SEMARANG",
  "MAKASSAR",
  "PALEMBANG",
  "TANGERANG",
  "DEPOK",
  "BOGOR",
  "BEKASI",
  "YOGYAKARTA",
  "MALANG",
  "SOLO",
  "PADANG",
  "DENPASAR",
  "BANJARMASIN",
  "PONTIANAK",
  "BALIKPAPAN",
  "MANADO",
  "PEKANBARU",
  "BATAM",
  "JAMBI",
  "BENGKULU",
  "LAMPUNG",
  "MATARAM",
  "KUPANG",
  "JAYAPURA",
  "AMBON",
  "TERNATE",
  "GORONTALO",
  "MAMUJU",
  "KENDARI",
  "PALU",
  "SAMARINDA",
  "BONTANG",
  "TARAKAN",
  "SINGKAWANG",
  "TANJUNG PINANG",
  "PANGKAL PINANG",
];

export const streetName = [
  "JL. MERDEKA",
  "JL. SUDIRMAN",
  "JL. THAMRIN",
  "JL. GATOT SUBROTO",
  "JL. IMAM BONJOL",
  "JL. DIPONEGORO",
  "JL. AHMAD YANI",
  "JL. GAJAH MADA",
  "JL. HAYAM WURUK",
  "JL. JUANDA",
  "JL. VETERAN",
  "JL. PAHLAWAN",
  "JL. PROKLAMASI",
  "JL. KEBON JERUK",
  "JL. RAYA JAKARTA",
  "JL. KEBAYORAN",
  "JL. MENTENG",
  "JL. CIKINI",
  "JL. SALEMBA",
  "JL. KRAMAT",
  "JL. MATRAMAN",
  "JL. JATINEGARA",
  "JL. CAWANG",
  "JL. TEBET",
  "JL. PANCORAN",
  "JL. MAMPANG",
  "JL. SENAYAN",
  "JL. BLOK M",
  "JL. RADIO DALAM",
  "JL. FATMAWATI",
];

export const village = [
  "CIKINI",
  "MENTENG",
  "GONDANGDIA",
  "KEBON SIRIH",
  "PETOJO UTARA",
  "GAMBIR",
  "DURI PULO",
  "KAMPUNG BALI",
  "TANAH ABANG",
  "BENDUNGAN HILIR",
  "KARET TENGSIN",
  "PETAMBURAN",
  "KEBON MELATI",
  "KEBON KACANG",
  "CIDENG",
  "PEKOJAN",
  "ROA MALAKA",
  "TAMBORA",
  "JEMBATAN LIMA",
  "KRENDANG",
  "DURI SELATAN",
  "DURI UTARA",
  "KAPUK",
  "KAMAL",
  "TEGAL ALUR",
  "PEGADUNGAN",
  "KALIDERES",
  "SEMANAN",
  "CENGKARENG BARAT",
  "CENGKARENG TIMUR",
];

export const subDistrict = [
  "MENTENG",
  "TANAH ABANG",
  "GAMBIR",
  "SAWAH BESAR",
  "KEMAYORAN",
  "SENEN",
  "CEMPAKA PUTIH",
  "JOHAR BARU",
  "TAMBORA",
  "TAMAN SARI",
  "KRUKUT",
  "GROGOL PETAMBURAN",
  "CENGKARENG",
  "KALIDERES",
  "KEBON JERUK",
  "PALMERAH",
  "KEMBANGAN",
  "PESANGGRAHAN",
  "KEBAYORAN LAMA",
  "KEBAYORAN BARU",
  "CILANDAK",
  "JAGAKARSA",
  "MAMPANG PRAPATAN",
  "PANCORAN",
  "TEBET",
  "SETIA BUDI",
  "MENTENG DALAM",
  "GUNTUR",
  "KUNINGAN",
  "SENAYAN",
];

export const religion = [
  "ISLAM",
  "KRISTEN",
  "KATOLIK",
  "HINDU",
  "BUDDHA",
  "KHONGHUCU",
];

export const maritalStatus = [
  "BELUM KAWIN",
  "KAWIN",
  "CERAI HIDUP",
  "CERAI MATI",
];

export const job = [
  // Pekerjaan Pemerintahan & Hukum
  "PEGAWAI NEGERI SIPIL",
  "TNI",
  "POLRI",
  "HAKIM",
  "JAKSA",
  "ADVOKAT",
  "NOTARIS",
  "PEJABAT PEMERINTAHAN",

  // Pekerjaan Swasta & Bisnis
  "KARYAWAN SWASTA",
  "WIRASWASTA",
  "PEDAGANG",
  "PENGUSAHA",
  "DIREKTUR",
  "MANAGER",
  "SUPERVISOR",
  "MARKETING",
  "SALES",
  "ADMINISTRASI",

  // Pendidikan & Akademik
  "GURU",
  "DOSEN",
  "KEPALA SEKOLAH",
  "TUTOR",
  "INSTRUKTUR",
  "PENELITI",
  "MAHASISWA",
  "PELAJAR",

  // Kesehatan & Medis
  "DOKTER",
  "PERAWAT",
  "BIDAN",
  "APOTEKER",
  "DOKTER GIGI",
  "AHLI GIZI",
  "FISIOTERAPIS",
  "PARAMEDIS",
  "RADIOGRAFER",

  // Pertanian & Perikanan
  "PETANI",
  "PETERNAK",
  "NELAYAN",
  "PEMBUDIDAYA IKAN",
  "BURUH TANI",

  // Teknik & Teknologi
  "TEKNISI",
  "MONTIR",
  "MEKANIK",
  "PROGRAMMER",
  "ANALIS SISTEM",
  "NETWORK ADMINISTRATOR",
  "IT SUPPORT",
  "ENGINEER",
  "ARSITEK",

  // Keuangan & Perbankan
  "AKUNTAN",
  "TELLER",
  "CUSTOMER SERVICE",
  "ANALIS KREDIT",
  "KONSULTAN KEUANGAN",
  "KASIR",

  // Transportasi & Logistik
  "SUPIR",
  "DRIVER",
  "OJEK ONLINE",
  "KURIR",
  "PILOT",
  "MASINIS",
  "KONDEKTUR",
  "EKSPEDISI",

  // Pelayanan & Hospitality
  "PRAMUSAJI",
  "RESEPSIONIS",
  "CHEF",
  "KOKI",
  "BARTENDER",
  "ROOM BOY",
  "HOUSEKEEPING",
  "SECURITY",
  "CLEANING SERVICE",

  // Media & Kreatif
  "WARTAWAN",
  "EDITOR",
  "FOTOGRAFER",
  "VIDEOGRAPHER",
  "DESAINER GRAFIS",
  "SENIMAN",
  "PENULIS",
  "CONTENT CREATOR",
  "YOUTUBER",
  "BLOGGER",
  "INFLUENCER",

  // Agama & Sosial
  "USTADZ",
  "PENDETA",
  "PASTOR",
  "IMAM",
  "GURU NGAJI",
  "MUBALIGH",
  "ROHANIWAN",

  // Konsultan & Profesi
  "KONSULTAN",
  "PSIKOLOG",
  "KONSELOR",
  "AUDITOR",
  "SURVEYOR",
  "MAKELAR",
  "AGEN ASURANSI",

  // Konstruksi & Kerajinan
  "TUKANG",
  "TUKANG BATU",
  "TUKANG KAYU",
  "TUKANG LAS",
  "TUKANG CAT",
  "BURUH BANGUNAN",
  "MANDOR",

  // Industri & Manufaktur
  "BURUH",
  "OPERATOR MESIN",
  "QUALITY CONTROL",
  "FOREMAN",
  "WELDER",

  // Lain-lain
  "PENSIUNAN",
  "IBU RUMAH TANGGA",
  "FREELANCER",
  "PEKERJA LEPAS",
  "TIDAK BEKERJA",
  "BELUM BEKERJA",
];

export const bloodType = ["A+", "A-", "B+", "B-", "AB+", "AB-", "O+", "O-"];
