/**
 * Seed geographic tables (provinces, regencies, districts, villages)
 * from upstream cahyadsn/wilayah dataset.
 *
 * Source of truth: `seeds/wilayah-seed.sql`, generated from cahyadsn/wilayah.
 *
 * Usage:
 *   npx tsx scripts/seed.ts          → remote D1
 *   npx tsx scripts/seed.ts --local  → local D1
 *   npx tsx scripts/seed.ts --refresh → regenerate seeds/wilayah-seed.sql
 */
import { execFileSync } from "node:child_process";
import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const __filename = fileURLToPath(import.meta.url);
const isMain = process.argv[1] === __filename;
const __dirname = dirname(__filename);

const DEFAULT_URL =
  "https://raw.githubusercontent.com/cahyadsn/wilayah/master/db/wilayah.sql";
const UPSTREAM_REPOSITORY_URL = "https://github.com/cahyadsn/wilayah";
const SEED_SQL_FILE = join(__dirname, "..", "seeds", "wilayah-seed.sql");

type Row = Record<string, unknown>;

const DEFAULT_BATCH_SIZE = 500;
const SEED_ORDER = ["provinces", "regencies", "districts", "villages"] as const;

function quoteIdent(name: string): string {
  return `"${name.replace(/"/g, '""')}"`;
}
function quoteValue(v: unknown): string {
  if (v === null || v === undefined) return "NULL";
  if (typeof v === "number") return Number.isFinite(v) ? String(v) : "NULL";
  if (typeof v === "boolean") return v ? "1" : "0";
  if (typeof v === "bigint") return v.toString();
  return `'${String(v).replace(/'/g, "''")}'`;
}

interface BuildSeedSqlOptions {
  batchSize?: number;
}

function buildInsert(
  table: string,
  rows: Row[],
  options: BuildSeedSqlOptions = {}
): string[] {
  if (rows.length === 0) return [];
  const batchSize = options.batchSize ?? DEFAULT_BATCH_SIZE;
  if (!Number.isInteger(batchSize) || batchSize < 1) {
    throw new Error(`Invalid batch size: ${batchSize}`);
  }
  const cols = Object.keys(rows[0]);
  const colList = cols.map(quoteIdent).join(", ");
  const updateList = cols
    .filter((col) => col !== "id")
    .map((col) => `${quoteIdent(col)} = excluded.${quoteIdent(col)}`)
    .join(", ");
  const stmts: string[] = [];
  for (let i = 0; i < rows.length; i += batchSize) {
    const batch = rows.slice(i, i + batchSize);
    const values = batch
      .map((r) => `(${cols.map((c) => quoteValue(r[c])).join(", ")})`)
      .join(",\n  ");
    stmts.push(
      `INSERT INTO ${quoteIdent(table)} (${colList}) VALUES\n  ${values}\nON CONFLICT("id") DO UPDATE SET ${updateList};`
    );
  }
  return stmts;
}

function buildSeedSql(
  parsed: ParsedWilayah,
  options: BuildSeedSqlOptions = {}
): string {
  const statements = [
    "-- Generated by scripts/seed.ts --refresh. Do not edit by hand.",
    `-- Source: ${UPSTREAM_REPOSITORY_URL}`,
    `-- Raw: ${DEFAULT_URL}`,
    "-- Data: Kode Wilayah sesuai Kepmendagri No. 300.2.2-2138 Tahun 2025.",
    "BEGIN TRANSACTION;",
  ];

  for (const table of SEED_ORDER) {
    statements.push(
      ...buildInsert(table, parsed[table], {
        batchSize: options.batchSize,
      })
    );
  }

  statements.push("COMMIT;");
  return `${statements.join("\n\n")}\n`;
}

function runWranglerFile(file: string, flag: string): void {
  const args = ["wrangler", "d1", "execute", "ktp-generator"];
  if (flag) args.push(flag);
  args.push("--file", file);
  execFileSync("npx", args, { encoding: "utf8", stdio: "inherit" });
}

function countRows(parsed: ParsedWilayah): number {
  return (
    parsed.provinces.length +
    parsed.regencies.length +
    parsed.districts.length +
    parsed.villages.length
  );
}

function countBatches(parsed: ParsedWilayah, batchSize: number): number {
  return SEED_ORDER.reduce(
    (total, table) => total + Math.ceil(parsed[table].length / batchSize),
    0
  );
}

// ------------------------------------------------------------------
// Parsing
// ------------------------------------------------------------------

interface ParsedWilayah {
  provinces: Row[];
  regencies: Row[];
  districts: Row[];
  villages: Row[];
}

function normalizeCode(kode: string): string {
  return kode.replace(/\./g, "");
}

function classify(kode: string): "province" | "regency" | "district" | "village" {
  const n = normalizeCode(kode);
  if (n.length === 2) return "province";
  if (n.length === 4) return "regency";
  if (n.length === 6) return "district";
  if (n.length === 10) return "village";
  throw new Error(`Unexpected code length ${n.length} for "${kode}"`);
}

function parseSqlInserts(sql: string): ParsedWilayah {
  // Strip line comments
  const cleaned = sql.replace(/^--.*$/gm, "");
  // Match INSERT ... VALUES (...),('a','b'),...;
  const insertRe = /INSERT\s+INTO\s+["'`]?wilayah["'`]?\s*\(([^)]+)\)\s*VALUES\s*([\s\S]*?);/gi;
  const result: ParsedWilayah = {
    provinces: [],
    regencies: [],
    districts: [],
    villages: [],
  };
  let match: RegExpExecArray | null;
  while ((match = insertRe.exec(cleaned)) !== null) {
    const values = match[2];
    const rowRe = /\(\s*'((?:[^'\\]|\\.)*)'\s*,\s*'((?:[^'\\]|\\.)*)'\s*\)/g;
    let r: RegExpExecArray | null;
    while ((r = rowRe.exec(values)) !== null) {
      const kode = r[1];
      const nama = r[2].replace(/\\'/g, "'");
      try {
        const kind = classify(kode);
        const n = normalizeCode(kode);
        if (kind === "province") {
          result.provinces.push({ id: n, name: nama });
        } else if (kind === "regency") {
          result.regencies.push({
            id: n,
            province_id: n.slice(0, 2),
            name: nama,
          });
        } else if (kind === "district") {
          result.districts.push({
            id: n,
            regency_id: n.slice(0, 4),
            province_id: n.slice(0, 2),
            name: nama,
          });
        } else {
          result.villages.push({
            id: n,
            district_id: n.slice(0, 6),
            regency_id: n.slice(0, 4),
            province_id: n.slice(0, 2),
            name: nama,
          });
        }
      } catch (err) {
        console.warn(`  ! Skipping invalid code "${kode}": ${(err as Error).message}`);
      }
    }
  }
  return enforceHierarchy(result);
}

function enforceHierarchy(parsed: ParsedWilayah): ParsedWilayah {
  const provinceIds = new Set(parsed.provinces.map((row) => String(row.id)));
  const regencyIds = new Set(parsed.regencies.map((row) => String(row.id)));
  const districtIds = new Set(parsed.districts.map((row) => String(row.id)));

  return {
    provinces: parsed.provinces,
    regencies: parsed.regencies.filter((row) =>
      provinceIds.has(String(row.province_id)),
    ),
    districts: parsed.districts.filter(
      (row) =>
        provinceIds.has(String(row.province_id)) &&
        regencyIds.has(String(row.regency_id)),
    ),
    villages: parsed.villages.filter(
      (row) =>
        provinceIds.has(String(row.province_id)) &&
        regencyIds.has(String(row.regency_id)) &&
        districtIds.has(String(row.district_id)),
    ),
  };
}

async function fetchUrl(url: string): Promise<string> {
  const res = await fetch(url);
  if (!res.ok) {
    throw new Error(`HTTP ${res.status} fetching ${url}`);
  }
  return res.text();
}

async function refreshSeedSqlFile(): Promise<void> {
  const batchSize = DEFAULT_BATCH_SIZE;

  console.log(`→ Fetching wilayah.sql from ${DEFAULT_URL}`);
  const sql = await fetchUrl(DEFAULT_URL);
  const parsed = parseSqlInserts(sql);
  const seedSql = buildSeedSql(parsed, { batchSize });
  const batches = countBatches(parsed, batchSize);
  const total = countRows(parsed);

  mkdirSync(dirname(SEED_SQL_FILE), { recursive: true });
  writeFileSync(SEED_SQL_FILE, seedSql);

  console.log(
    `→ Wrote ${SEED_SQL_FILE} from ${total} upstream rows (${batches} batches)`
  );
  console.log(
    `  parsed: ${parsed.provinces.length} provinces, ${parsed.regencies.length} regencies, ${parsed.districts.length} districts, ${parsed.villages.length} villages`
  );
}

// ------------------------------------------------------------------
// CLI
// ------------------------------------------------------------------

async function main(): Promise<void> {
  const args = process.argv.slice(2);
  if (args.includes("--refresh")) {
    await refreshSeedSqlFile();
    return;
  }

  const local = args.includes("--local");
  const flag = local ? "" : "--remote";
  const target = local ? "local D1" : "remote D1";

  console.log(`→ Seeding ${target} from ${SEED_SQL_FILE}`);
  runWranglerFile(SEED_SQL_FILE, flag);
  console.log(`\n✓ Seeded ${target}`);
}

if (isMain) {
  main().catch((err) => {
    console.error(err);
    process.exit(1);
  });
}

export type { ParsedWilayah };
export {
  parseSqlInserts,
  fetchUrl,
  buildInsert,
  buildSeedSql,
  refreshSeedSqlFile,
  quoteIdent,
  quoteValue,
};
